version: '3'
services:
  wordpress:
    depends_on:
      - db # we use depends_on to insure the start sequence of the containers 
    image: wordpress
    networks:
      - my-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: mydb

  db:
    image: mysql
    environment: # instantiate mysql with these credentials and make wordpress consume them
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'verysecret'
    networks:
      - my-network

  loadbalancer-nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf #we voliume in the file nginx.conf on the specified container path
    networks:
      - my-network
    ports:
      - 80:80 # make nginx expose port 80 (port 80 is visible to the outside world)
    depends_on:
      - db
      - wordpress

networks:
  my-network: # a shared network for each container to communicate on